/***
*
*	Copyright (c) 1996-1997, Valve LLC. All rights reserved.
*
*	This product contains software technology licensed from Id
*	Software, Inc. ("Id Technology").  Id Technology (c) 1996 Id Software, Inc.
*	All Rights Reserved.
*
****/

// qc.cpp: writes the .qc script

#include "mdldec.h"

void CMDLDecompiler::QC_GenerateScript()
{
	if (!m_pstudiohdr)
		return;

	char qcfilename[_MAX_PATH];
	char path[_MAX_PATH];

	GetModelName();
	sprintf(qcfilename, "%s%s.qc", DestPath, ModelName);

	strcpy(path, ".");

	qcfile = fopen(qcfilename, "w");
	if (!qcfile)
	{
		LogMessage(MDLDEC_MSG_ERROR, "ERROR: Can't write %s\r\n", qcfilename);
		return;
	}

	fprintf(qcfile, "/*\n");
	fprintf(qcfile, "==============================================================================\n\n");
	fprintf(qcfile, "QC script generated by Half-Life Alpha MDL Decompiler v%s.\n", MDLDEC_VERSION);
	fprintf(qcfile, "%s.qc\n", ModelName);
	fprintf(qcfile, "Original model name: %s\n\n", m_pstudiohdr->name);
	fprintf(qcfile, "==============================================================================\n");
	fprintf(qcfile, "*/\n\n");

	fprintf(qcfile, "$modelname \"%s.mdl\"\n", ModelName);
	fprintf(qcfile, "$cd \"%s\\\"\n", path);
	fprintf(qcfile, "$cdtexture \"%s\\maps_8bit\\\"\n", path);
	fprintf(qcfile, "$scale 1.0\n");

	if (m_pstudiohdr->numtextures == 0)
		fprintf(qcfile, "$externaltextures\n");

	fprintf(qcfile, "\n");

	QC_WriteBodyModels();
	QC_WriteTextureGroups();
	QC_WriteBoneControllers();
	QC_WriteSequences();

	fprintf(qcfile, "\n// End of QC file.\n");
	fclose(qcfile);
	qcfile = NULL;

	LogMessage(MDLDEC_MSG_INFO, "QC Script: %s\r\n", qcfilename);
}

void CMDLDecompiler::QC_WriteTextureGroups()
{
	if (!m_ptexturehdr || !qcfile)
		return;

	studiohdr_t *phdr = m_ptexturehdr;
	if (phdr->numskinfamilies <= 1 || phdr->numskinref <= 0)
		return;

	short *pskinref = (short *)((byte *)phdr + phdr->skinindex);
	mstudiotexture_t *ptextures = (mstudiotexture_t *)((byte *)phdr + phdr->textureindex);

	fprintf(qcfile, "\n// %i skin families\n", phdr->numskinfamilies);
	fprintf(qcfile, "$texturegroup skinfamilies\n{\n");

	for (int i = 0; i < phdr->numskinfamilies; i++)
	{
		fprintf(qcfile, "{");
		for (int j = 0; j < phdr->numskinref; j++)
		{
			fprintf(qcfile, " \"%s\"", ptextures[pskinref[i * phdr->numskinref + j]].name);
		}
		fprintf(qcfile, " }\n");
	}

	fprintf(qcfile, "}\n");
}

void CMDLDecompiler::QC_WriteBodyModels()
{
	if (!m_pstudiohdr || !qcfile)
		return;

	fprintf(qcfile, "\n// reference meshes\n");

	mstudiobodyparts_t *pbodyparts = (mstudiobodyparts_t *)((byte *)m_pstudiohdr + m_pstudiohdr->bodypartindex);

	for (int i = 0; i < m_pstudiohdr->numbodyparts; i++)
	{
		mstudiomodel_t *pmodels = (mstudiomodel_t *)((byte *)m_pstudiohdr + pbodyparts[i].modelindex);
		char tmpname[sizeof(pmodels->name)];

		if (pbodyparts[i].nummodels == 1)
		{
			strncpy(tmpname, pmodels[0].name, sizeof(tmpname) - 1);
			tmpname[sizeof(tmpname) - 1] = 0;
			MyExtractFileBase(tmpname, tmpname);
			fprintf(qcfile, "$body %s \"%s\"\n\n", pbodyparts[i].name, tmpname);
			continue;
		}

		fprintf(qcfile, "$bodygroup %s\n", pbodyparts[i].name);
		fprintf(qcfile, "{\n");
		for (int j = 0; j < pbodyparts[i].nummodels; j++)
		{
			if (_strnicmp(pmodels[j].name, "blank", strlen("blank")) == 0)
			{
				fprintf(qcfile, "blank\n");
				continue;
			}

			strncpy(tmpname, pmodels[j].name, sizeof(tmpname) - 1);
			tmpname[sizeof(tmpname) - 1] = 0;
			MyExtractFileBase(tmpname, tmpname);
			fprintf(qcfile, "studio \"%s\"\n", tmpname);
		}
		fprintf(qcfile, "}\n");
	}
}

void CMDLDecompiler::QC_WriteBoneControllers()
{
	if (!m_pstudiohdr || !qcfile || m_pstudiohdr->numbonecontrollers <= 0)
		return;

	mstudiobonecontroller_t *pcontrollers = (mstudiobonecontroller_t *)((byte *)m_pstudiohdr + m_pstudiohdr->bonecontrollerindex);

	fprintf(qcfile, "\n// %i bone controllers\n", m_pstudiohdr->numbonecontrollers);
	for (int i = 0; i < m_pstudiohdr->numbonecontrollers; i++)
	{
		char mflag[64];
		QC_TranslateMotionFlag(pcontrollers[i].type & ~STUDIO_RLOOP, mflag, false);

		char boneName[64];
		GetBoneName(pcontrollers[i].bone, boneName, sizeof(boneName));

		fprintf(qcfile, "$controller %i \"%s\" %s %f %f", i, boneName, mflag[0] ? mflag : "X", pcontrollers[i].start, pcontrollers[i].end);

		if (pcontrollers[i].type & STUDIO_RLOOP)
			fprintf(qcfile, " loop");
		fprintf(qcfile, "\n");
	}
}

void CMDLDecompiler::QC_WriteSequences()
{
	if (!m_pstudiohdr || !qcfile)
		return;

	fprintf(qcfile, "\n// %i animation sequences\n", m_pstudiohdr->numseq);

	for (int i = 0; i < m_pstudiohdr->numseq; i++)
	{
		const mstudioseqdesc_t *pseqdesc = GetSequenceDesc(i);
		if (!pseqdesc)
			continue;

		fprintf(qcfile, "$sequence \"%s\" \"%s\" ", pseqdesc->label, pseqdesc->label);

		if (pseqdesc->motiontype != 0)
		{
			char flagstring[128];
			QC_TranslateMotionFlag(pseqdesc->motiontype, flagstring, true);
			fprintf(qcfile, "%s ", flagstring);
		}

		fprintf(qcfile, "fps %.0f ", pseqdesc->fps);
		if (pseqdesc->flags & STUDIO_LOOPING)
			fprintf(qcfile, "loop ");

		bool wroteEvents = false;

		// StudioMDL also stores the events with their options, prefer those
		if (pseqdesc->numfullevents > 0)
		{
			size_t eventOffset = (size_t)pseqdesc->fulleventindex;
			size_t eventBytes = (size_t)pseqdesc->numfullevents * sizeof(mstudiofullevent_t);

			if (eventOffset > 0 && eventOffset + eventBytes <= CoreFile.size())
			{
				const mstudiofullevent_t *pevents = (const mstudiofullevent_t *)(CoreFile.data() + eventOffset);

				fprintf(qcfile, "{\n");
				for (int j = 0; j < pseqdesc->numfullevents; j++)
				{
					fprintf(qcfile, "event %d %d", pevents[j].event, pevents[j].frame);
					if (pevents[j].options[0] != 0)
						fprintf(qcfile, " \"%s\"", pevents[j].options);
					fprintf(qcfile, "\n");
				}
				fprintf(qcfile, "}\n");
				wroteEvents = true;
			}
		}

		if (!wroteEvents && pseqdesc->numevents > 0 && pseqdesc->numevents <= MAXSTUDIOEVENTS)
		{
			size_t eventOffset = (size_t)pseqdesc->eventindex;
			size_t eventBytes = (size_t)pseqdesc->numevents * sizeof(mstudioevent_t);

			if (eventOffset > 0 && eventOffset + eventBytes <= CoreFile.size())
			{
				const mstudioevent_t *pevents = (const mstudioevent_t *)(CoreFile.data() + eventOffset);

				fprintf(qcfile, "{\n");
				for (int j = 0; j < pseqdesc->numevents; j++)
				{
					fprintf(qcfile, "event %u %d\n", (unsigned int)pevents[j].event, (int)pevents[j].frame);
				}
				fprintf(qcfile, "}\n");
				wroteEvents = true;
			}
		}

		if (!wroteEvents)
		{
			fprintf(qcfile, "\n");

			if (pseqdesc->numfullevents > 0 || pseqdesc->numevents > 0)
			{
				LogMessage(MDLDEC_MSG_WARNING, "WARNING: Sequence \"%s\" has invalid events block (modern index=%d count=%d, legacy index=%d count=%d).\r\n",
					pseqdesc->label, pseqdesc->fulleventindex, pseqdesc->numfullevents, pseqdesc->eventindex, pseqdesc->numevents);
			}
		}
	}
}

//=========================================================
// QC_TranslateMotionFlag - the qc name of one flag, or with
// addtostring, of every flag set
//=========================================================
void CMDLDecompiler::QC_TranslateMotionFlag(int mflag, char *string, bool addtostring)
{
	static const struct
	{
		int flag;
		const char *name;
	} motionflags[] =
	{
		{ STUDIO_X, "X" },
		{ STUDIO_Y, "Y" },
		{ STUDIO_Z, "Z" },
		{ STUDIO_XR, "XR" },
		{ STUDIO_YR, "YR" },
		{ STUDIO_ZR, "ZR" },
		{ STUDIO_LX, "LX" },
		{ STUDIO_LY, "LY" },
		{ STUDIO_LZ, "LZ" },
		{ STUDIO_AX, "AX" },
		{ STUDIO_AY, "AY" },
		{ STUDIO_AZ, "AZ" },
		{ STUDIO_AXR, "XRT" },
		{ STUDIO_AYR, "YRT" },
		{ STUDIO_AZR, "ZRT" },
	};

	string[0] = 0;

	if (!addtostring)
	{
		strcpy(string, "X");
		for (size_t i = 0; i < sizeof(motionflags) / sizeof(motionflags[0]); i++)
		{
			if (mflag == motionflags[i].flag)
			{
				strcpy(string, motionflags[i].name);
				break;
			}
		}
		return;
	}

	for (size_t i = 0; i < sizeof(motionflags) / sizeof(motionflags[0]); i++)
	{
		if (mflag & motionflags[i].flag)
		{
			strcat(string, " ");
			strcat(string, motionflags[i].name);
		}
	}
}
